# -*- coding: utf-8 -*-
"""Tradudor_DIO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gd-55eX3ixw5xaUWuhxaZOgulQU204Fp
"""

!pip install requests python-docx



from inspect import Parameter
import requests
from docx import Document
import os
subscription_key = "GIOBchaEZQWZACeGKzeIAxZu7aQJk0SAEoblfNSKESOjcLPgmgYiJQQJ99BJACHYHv6XJ3w3AAAbACOGX9vE"
endpoint = 'https://api.cognitive.microsofttranslator.com'
location = "eastus2"
language_destination = "pt-br"

def translator_text(text, target_language):
    path = '/translate'
    constructed_url = endpoint + path
    header = {
        'Ocp-Apim-Subscription-Key': subscription_key,
        'Ocp-Apim-Subscription-Region': location,
        'Content-type': 'application/json',
        'X-ClientTraceId': str(os.urandom(16))
    }

    body = [{
        'text': text
    }]
    params={
        'api-version': '3.0',
        'from': 'en',
        'to': target_language
    }

    request = requests.post(constructed_url, params=params, headers=header, json=body)
    response = request.json()
    return response[0]["translations"][0]["text"]

translator_text("I am a man who walks alone", language_destination)

def translate_document(path):
  document = Document(path)
  full_text = []
  for paragraph in document.paragraphs:
    translated_text = translator_text(paragraph.text, language_destination)
    full_text.append(translated_text)

  translated_doc = Document()
  for line in full_text:
    translated_doc.add_paragraph(line)
  path_translated = path.replace(".docx", f"_{language_destination}.docx")
  translated_doc.save(path_translated)
  return path_translated
input_file = "/content/MUSICA.docx"
translate_document(input_file)